#!/usr/bin/env bash
set -o errexit

################################################################
# Program: ngseasy_fastqc
# Version 1.0-r001
# Author: Stephen Newhouse (stephen.j.newhouse@gmail.com); Amos Folarin (amosfolarin@gmail.com)
###########################################################################################
#
#    Copyright (C) 2015  Stephen Jeffrey Newhouse
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
###########################################################################################

########################################################################################################
## Set version and run date
########################################################################################################
NGSEASYVERSION="1.0-r001"
RUNDATE=`date +"%d%m%y"`
NGSEASY_STEP="ngseasy_fastqc"

echo -e "\n################################################################"
echo -e "# Program: ${NGSEASY_STEP}"
echo -e "# Version ${NGSEASYVERSION}"
echo -e "# Authors: Stephen Newhouse (stephen.j.newhouse@gmail.com); Amos Folarin (amosfolarin@gmail.com)"
echo -e "#"
echo -e "# Copyright (C) 2015  Stephen Jeffrey Newhouse and Amos Folarin"
echo -e "# NGSeasy (aka ngseasy) Version ${NGSEASYVERSION} comes with ABSOLUTELY NO WARRANTY;"
echo -e "# for details see the GNU General Public License."
echo -e "# This is free software, and you are welcome to redistribute it under certain conditions;"
echo -e "# see the GNU General Public License for details."
echo -e "#"
echo -e "###########################################################################################\n\n"

########################################################################################################
## docker options
########################################################################################################
## DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman"

########################################################################################################
## global logging fuction
########################################################################################################
function logger_ngseasy() {
 message=${1}
 mylogfile=${2}
 echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
 echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
}

########################################################################################################
## global usage
########################################################################################################
function ngseasy_fastqc_usage() {
    echo "
Program: ngseasy_fastqc
Version 1.0-r001
Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)

usage:   ngseasy_fastqc -c <config_file> -d <project_directory>

options:  -c  STRING	configuration file
          -d  STRING	project directory
          -j  STRING    job name
          -w  STRING    job dependency string
          -h  NULL	show this message

ngseasy_fastqc sets up the NGSeasy docker fastqc container compbio/ngseasy-fastq:VERSION and runs fastq on raw fastq files.

This is is optomised for PE data, and calls 2 threads as default to process the 2 PE .fastq file simultaneously.
"
}

########################################################################################################
## RELPATH
########################################################################################################

function relpath() { 
  python -c "import os,sys;print(os.path.relpath(*(sys.argv[1:])))" "$@";
}

########################################################################################################
## get options for command line args
########################################################################################################
  while  getopts "hc:d:j:w:" opt
  do

      case ${opt} in
	  h)
	  ngseasy_fastqc_usage #print help
	  exit 0
	  ;;

	  c)
	  config_tsv=${OPTARG}
	  ;;

	  d)
	  project_directory=${OPTARG}
	  ;;

	  j)
      job_name=${OPTARG}
      ;;

      w)
      dependency=${OPTARG}
      ;;
      esac
  done
###########################################################################################
## Check options passed in.
###########################################################################################

if [[ -z "$config_tsv" ]]; then
    echo -e "ERROR: No options were passed. Exiting"
    sleep 1s
    ngseasy_fastqc_usage
    sleep 1s
    exit 1
fi

########################################################################################################
## check project_directory exists.
########################################################################################################
if [[ ! -d "${project_directory}" ]]; then
  echo -e "[${NGSEASY_STEP}]:ERROR : project_directory [${project_directory}] does not exist"
  ngseasy_fastqc_usage;
  exit 1;
fi

########################################################################################################
## creating default log file
########################################################################################################

PWD=`pwd`
LOGDIR=${project_directory}/run_logs
TMP=${project_directory}/ngseasy_tmp
RUNLOG=${LOGDIR}/ngseasy.${config_tsv}.${RUNDATE}

if [[ ! -e ${LOGDIR} ]]; then
  mkdir ${LOGDIR}
fi

if [[ ! -e "${RUNLOG}.log" ]]; then
  touch ${RUNLOG}.log
fi

logger_ngseasy "[${NGSEASY_STEP}]:Top Level Project Directory [${project_directory}]"  ${RUNLOG}

########################################################################################################
## check config file exists.
########################################################################################################
if [[ ! -e "${config_tsv}" ]]; then
  echo -e "[${NGSEASY_STEP}]:ERROR : [${config_tsv}] does not exist....exiting"
  ngseasy_fastqc_usage;
  exit 1;
fi

logger_ngseasy "[${NGSEASY_STEP}]:Configuration file found [${config_tsv}] " ${RUNLOG}

###########################################################################################
## check Num feilds in  ${config_tsv}
###########################################################################################
logger_ngseasy "[${NGSEASY_STEP}]:Reading [${config_tsv}] " ${RUNLOG}
logger_ngseasy "[${NGSEASY_STEP}]:Checking number of feilds in  [${config_tsv}] " ${RUNLOG}

numcols=`awk '{ print NF }' ${config_tsv} | sort -g | head -1`

if [[  "$numcols" -lt 23 ]]; then
  logger_ngseasy "[${NGSEASY_STEP}]:ERROR: [${config_tsv}] format issue. Check your file! " ${RUNLOG}
  exit 1;
fi

logger_ngseasy "[${NGSEASY_STEP}]:Number of expected columns [$numcols] of [${config_tsv}] ok...proceeding... " ${RUNLOG}

###########################################################################################
## Read config file
###########################################################################################
## check ${config_tsv}. is this a batch file or the orginal config file
#
logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${RUNLOG}

hasheader=`sed 1q ${config_tsv} | grep PROJECT_ID | wc -l | awk '{print $1}'`

if [[ "${config_tsv}" == *.batch.* ]]; then
  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${RUNLOG}
fi

CONFIG=${config_tsv}

if [[ "$hasheader" -eq 1 ]]; then
  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${RUNLOG}
  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${RUNLOG}
  sed 1d ${config_tsv} > ${TMP}/${config_tsv}.tmp
  CONFIG="${TMP}/${config_tsv}.tmp"
fi

CONFIG_NAME=$(basename "$CONFIG")
CONFIG=$(cd $(dirname "$CONFIG") && pwd -P)/${CONFIG_NAME}

logger_ngseasy "[${NGSEASY_STEP}]:Setting CONFIG to [${CONFIG}]" ${RUNLOG}

# filter lines with fastqc == qc-fastqc
awk '{ if ($12 == "qc-fastqc") print }' ${CONFIG} > ${TMP}/${CONFIG_NAME}.qc-fastqc
awk '{ if ($12 != "qc-fastqc" && $12 != "no-fastqc") print }' ${CONFIG} > ${TMP}/${CONFIG_NAME}.err-fastqc

err_samples=`wc -l ${RUNFILE}.err-fastqc | awk '{print $1}'`

if [[ "${err_samples}" -gt 0 ]]; then
  logger_ngseasy "[${NGSEASY_STEP}]:ERROR: FASTQC option is not set. Should be one of [qc-fastqc] or [no-fastqc]: see ${RUNFILE}.err-fastqc file" ${RUNLOG}
  sleep 1s
  exit 1
fi

RUNFILE=${TMP}/${CONFIG_NAME}.qc-fastqc
RUNFILE_NAME=$(basename "$RUNFILE")

logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${RUNLOG}

RUNFILE_PIPEMAN=/home/pipeman/ngs_projects/$(relpath $RUNFILE ${project_directory})

logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE_PIPEMAN to [${RUNFILE_PIPEMAN}]" ${RUNLOG}

CMD=`which  ngseasy_fastqc_local`

logger_ngseasy "LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS=\"${DOCKER_OPTS} -v ${project_directory}:/home/pipeman/ngs_projects\"  bsub \
  -J \"${job_name}\" -w \"${dependency}\" -q docker_queue -o \"${LOGDIR}/${RUNFILE_NAME}.job.out\" -e \"${LOGDIR}/${RUNFILE_NAME}.job.err\" ${CMD} -c ${RUNFILE_PIPEMAN}" ${RUNLOG}

LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${project_directory}:/home/pipeman/ngs_projects"  bsub \
  -J "${job_name}" -w "${dependency}" -q docker_queue -o "${LOGDIR}/${RUNFILE_NAME}.job.out" -e "${LOGDIR}/${RUNFILE_NAME}.job.err" ${CMD} -c ${RUNFILE_PIPEMAN}
