FROM ubuntu:14.04
MAINTAINER Matthew Davis email: matdavis at ebi.ac.uk
# Initially created by Natalja Kurbatova
# Update the image with the latest packages (recommended)
# and install missing packages
##############################
# Perl multithreaded version
#############################
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \ 
	build-essential \     
        libcurl4-openssl-dev \
        libxml2-dev \
        gnupg \
        wget \
        zip \
        gcc \
        curl \
        procps \
        samtools \
        bowtie \
        && rm -fr /var/lib/apt/lists/*

# PERL
RUN mkdir /usr/src/perl
COPY *.patch /usr/src/perl/
WORKDIR /usr/src/perl

RUN curl -SL https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.22.0.tar.bz2 -o perl-5.22.0.tar.bz2 \
    && echo '400338c91c56420d98142cbfcb84d418cae2c98c *perl-5.22.0.tar.bz2' | sha1sum -c - \
    && tar --strip-components=1 -xjf perl-5.22.0.tar.bz2 -C /usr/src/perl \
    && rm perl-5.22.0.tar.bz2 \
    && cat *.patch | patch -p1 \
    && ./Configure -Dusethreads -Duse64bitall  -des \
    && make -j$(nproc) \
    && make test_harness \
    && make install \
    && cd /usr/src \
    && curl -LO https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm \
    && chmod +x cpanm \
    && ./cpanm App::cpanminus \
    && rm -fr ./cpanm /root/.cpanm /usr/src/perl

WORKDIR /root

CMD ["perl5.22.0","-de0"]

# R
RUN sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
RUN gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
RUN gpg -a --export E084DAB9 | sudo apt-key add -
RUN apt-get update
RUN apt-get -y install r-base

#setup R configs
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile
RUN Rscript -e "install.packages('R.utils')"
RUN Rscript -e "install.packages('RColorBrewer')"
RUN Rscript -e "install.packages('futile.logger')"
RUN Rscript -e "install.packages('snow')"
RUN Rscript -e "install.packages('bitops')"
RUN Rscript -e "install.packages('hwriter')"
RUN Rscript -e "install.packages('latticeExtra')"
RUN Rscript -e "install.packages('gplots')"
RUN Rscript -e "install.packages('BiocInstaller', repos='http://bioconductor.org/packages/3.1/bioc')"
RUN Rscript -e "install.packages('S4Vectors', repos='http://bioconductor.org/packages/3.1/bioc')"
RUN Rscript -e "install.packages('IRanges', repos='http://bioconductor.org/packages/3.1/bioc')"
RUN Rscript -e "install.packages('GenomicRanges', repos='http://bioconductor.org/packages/3.1/bioc')"
RUN Rscript -e "install.packages('ShortRead', repos='http://bioconductor.org/packages/3.1/bioc')"

RUN mkdir /kraken
WORKDIR /kraken
RUN wget ftp://ftp.ebi.ac.uk/pub/contrib/enrightlab/kraken/SequenceImp/src/seqimp-latest.tgz
RUN tar -xzf seqimp-latest.tgz
RUN wget ftp://ftp.ebi.ac.uk/pub/contrib/enrightlab/kraken/reaper/binaries/reaper-15-065/linux/tally-15-065
RUN wget ftp://ftp.ebi.ac.uk/pub/contrib/enrightlab/kraken/reaper/binaries/reaper-15-065/linux/swan-15-065
RUN wget ftp://ftp.ebi.ac.uk/pub/contrib/enrightlab/kraken/reaper/binaries/reaper-15-065/linux/reaper-15-065
RUN wget ftp://ftp.ebi.ac.uk/pub/contrib/enrightlab/kraken/reaper/binaries/reaper-15-065/linux/minion-15-065
RUN mv /kraken/reaper-15-065 /usr/bin/reaper
RUN mv /kraken/tally-15-065 /usr/bin/tally
RUN mv /kraken/swan-15-065 /usr/bin/swan
RUN mv /kraken/minion-15-065 /usr/bin/minion
RUN mv /kraken/seqimp*/ /kraken/seqimp

RUN chmod 771 /usr/bin/reaper
RUN chmod 771 /usr/bin/tally
RUN chmod 771 /usr/bin/swan
RUN chmod 771 /usr/bin/minion
ENV PATH /kraken/seqimp/bin:$PATH

RUN /kraken/seqimp/bin/imp_commandline.pl --system-check

# Annotations 9.7 GB ftp://ftp.ebi.ac.uk/pub/contrib/enrightlab/kraken/annotation/Annotation-12-164.tgz
# ftp.ebi.ac.uk - 193.62.192.4 (28/09/2015)

#ENTRYPOINT ["kraken"]
